export const InputFileTypes = [
  "Select",
  "FIR",
  "482",
  "Complaint",
  "Charge Sheet",
  "Order",
  "Notice",
  "Petition",
  "Written Statement",
  "Judgement",
  "Order sheet",
  "Writ Petition",
  "Response to Appeals",
  "enactments",
  "precedents",
  "interlocutory_application",
  "OCR",
  "OCR Format"
];

export const OutputTypes = [
  { name: "Select", disabled: false },
  { name: "appeal", disabled: false },
  { name: "petition", disabled: false },
  { name: "written_statement", disabled: false },
  { name: "482", disabled: false },
  { name: "writ_petition", disabled: false },
  { name: "impleading_application", disabled: false },
  { name: "injunction_app", disabled: false },
  { name: "criminal_appeal", disabled: true },
  { name: "response_to_appeal", disabled: true },
  { name: "notices", disabled: false },
  { name: "revision_petition", disabled: true },
  { name: "criminal_petition", disabled: true },
  { name: "criminal_complaint", disabled: true },
  { name: "consumer_complaint", disabled: true },
  { name: "version_consumercourts", disabled: true },
  { name: "translations", disabled: false },
  { name: "translations_kannada", disabled: false },
  { name: "summarisations", disabled: false },
  { name: "ocr", disabled: false },
  { name: "ocr_format", disabled: false },
  { name: "case_notes", disabled: false }
];
